//! Runtime configuration (`/etc/vexnas/config.toml`, generated by the NixOS module).

use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Config {
    pub server: ServerConfig,
    pub tls: TlsConfig,
    pub auth: AuthConfig,
    pub paths: PathsConfig,
    pub helper: HelperConfig,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ServerConfig {
    pub listen: Vec<String>,
    pub port: u16,
    pub assets_path: PathBuf,
    /// Sources allowed to connect at all (checked before the TLS handshake).
    pub allowed_cidrs: Vec<String>,
}

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct TlsConfig {
    /// Both set → use this certificate; both unset → generate a self-signed one.
    pub cert_file: Option<PathBuf>,
    pub key_file: Option<PathBuf>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct AuthConfig {
    pub admin_group: String,
    pub viewer_group: Option<String>,
    pub idle_minutes: i64,
    pub absolute_hours: i64,
    /// How often group membership is re-checked against the helper.
    pub recheck_minutes: i64,
    pub login_rate_limit_attempts: u32,
    pub login_rate_limit_window_secs: u64,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct PathsConfig {
    pub data_dir: PathBuf,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct HelperConfig {
    pub socket: PathBuf,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            listen: vec!["0.0.0.0".into(), "::".into()],
            port: 7290,
            assets_path: PathBuf::from("assets"),
            allowed_cidrs: [
                "127.0.0.0/8",
                "::1/128",
                "10.0.0.0/8",
                "172.16.0.0/12",
                "192.168.0.0/16",
                "fc00::/7",
                "fe80::/10",
                "100.64.0.0/10",
                "fd7a:115c:a1e0::/48",
            ]
            .map(String::from)
            .to_vec(),
        }
    }
}

impl Default for AuthConfig {
    fn default() -> Self {
        Self {
            admin_group: "wheel".into(),
            viewer_group: None,
            idle_minutes: 30,
            absolute_hours: 8,
            recheck_minutes: 5,
            login_rate_limit_attempts: 10,
            login_rate_limit_window_secs: 60,
        }
    }
}

impl Default for PathsConfig {
    fn default() -> Self {
        Self {
            data_dir: PathBuf::from("/var/lib/vexnas"),
        }
    }
}

impl Default for HelperConfig {
    fn default() -> Self {
        Self {
            socket: PathBuf::from("/run/vexnas/helper.sock"),
        }
    }
}

impl Config {
    /// Load from `path`. A missing file yields the defaults (dev convenience);
    /// a present-but-invalid file is an error.
    pub fn load(path: &Path) -> Result<Self, String> {
        let cfg: Config = match std::fs::read_to_string(path) {
            Ok(text) => toml::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Config::default(),
            Err(e) => return Err(format!("{}: {e}", path.display())),
        };
        cfg.validate()?;
        Ok(cfg)
    }

    pub fn validate(&self) -> Result<(), String> {
        if self.auth.admin_group.trim().is_empty() {
            return Err("auth.admin_group must not be empty".into());
        }
        if self.auth.viewer_group.as_deref() == Some(self.auth.admin_group.as_str()) {
            return Err("auth.viewer_group must differ from auth.admin_group".into());
        }
        if self.auth.idle_minutes < 1
            || self.auth.absolute_hours < 1
            || self.auth.recheck_minutes < 1
        {
            return Err("auth timeouts must be at least 1".into());
        }
        if self.tls.cert_file.is_some() != self.tls.key_file.is_some() {
            return Err("tls.cert_file and tls.key_file must be set together".into());
        }
        if self.server.listen.is_empty() {
            return Err("server.listen must not be empty".into());
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_are_valid() {
        Config::default().validate().unwrap();
    }

    #[test]
    fn unknown_keys_are_rejected() {
        assert!(toml::from_str::<Config>("[server]\nbogus = 1\n").is_err());
    }

    #[test]
    fn partial_file_fills_defaults() {
        let cfg: Config = toml::from_str("[auth]\nadmin_group = \"nas-admins\"\n").unwrap();
        assert_eq!(cfg.auth.admin_group, "nas-admins");
        assert_eq!(cfg.server.port, 7290);
    }

    #[test]
    fn invalid_combinations_are_rejected() {
        let mut cfg = Config::default();
        cfg.tls.cert_file = Some("/x".into());
        assert!(cfg.validate().is_err());

        let mut cfg = Config::default();
        cfg.auth.viewer_group = Some(cfg.auth.admin_group.clone());
        assert!(cfg.validate().is_err());
    }
}
